# Generated by Django 4.1.6 on 2023-02-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prices_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.DateTimeField()),
                ('symbol', models.CharField(max_length=10)),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('volume', models.FloatField()),
                ('close_time', models.DateTimeField()),
                ('quote_asset_volume', models.FloatField()),
                ('number_of_trades', models.FloatField()),
                ('taker_buy_base_asset_volume', models.FloatField()),
                ('taker_buy_quote_asset_volume', models.FloatField()),
                ('ignore', models.IntegerField()),
            ],
            options={
                'unique_together': {('open_time', 'symbol')},
            },
        ),
    ]
