# Generated by Django 4.1.6 on 2023-02-05 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices_db',
            name='close_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='prices_db',
            name='open_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
