# Generated by Django 4.1.6 on 2023-02-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybot', '0002_alter_prices_db_close_time_alter_prices_db_open_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices_db',
            name='symbol',
            field=models.CharField(max_length=13),
        ),
    ]
